_target_: hyperbox.models.darts_model.DARTSModel

network_cfg:
    _target_: hyperbox.networks.resnet.resnet20
mutator_cfg:
    _target_: hyperbox.mutator.darts_mutator.DartsMutator
loss_cfg:
    _target_: torch.nn.CrossEntropyLoss
optimizer_cfg:
    _target_: torch.optim.Adam
    lr: 0.001
    weight_decay: 0.0005
metric_cfg:
    _target_: torchmetrics.classification.accuracy.Accuracy