_target_: hyperbox.models.random_nas_model.RandomModel

defaults:
    - network_cfg: finegrained_resnet
    - mutator_cfg: random_mutator
    - optimizer_cfg: adam
    - metric_cfg: accuracy
    - loss_cfg: cross_entropy
