_target_: src.datamodules.mnist_datamodule.MNISTDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 8
train_val_test_split: [160, 160, 160]
num_workers: 0
pin_memory: False
