trainer:
  _target_: pytorch_lightning.Trainer
  checkpoint_callback: true
  default_root_dir: null
  gradient_clip_val: 0.0
  process_position: 0
  num_nodes: 1
  num_processes: 1
  gpus: 1
  auto_select_gpus: false
  tpu_cores: null
  log_gpu_memory: null
  progress_bar_refresh_rate: 0
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 5
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 180
  min_epochs: 1
  max_steps: null
  min_steps: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  val_check_interval: 1.0
  flush_logs_every_n_steps: 100
  log_every_n_steps: 10
  accelerator: horovod
  sync_batchnorm: false
  precision: 32
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  truncated_bptt_steps: null
  resume_from_checkpoint: null
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: true
  terminate_on_nan: false
  auto_scale_batch_size: false
  prepare_data_per_node: true
  plugins: null
  amp_backend: native
  amp_level: O2
  move_metrics_to_cpu: false
model:
  network_cfg:
    _target_: hyperbox.networks.ofa.OFAMobileNetV3
    kernel_size_list:
    - 3
    - 5
    - 7
    expand_ratio_list:
    - 4
    - 6
    depth_list:
    - 3
    - 4
    base_stage_width:
    - 16
    - 16
    - 24
    - 40
    - 80
    - 112
    - 160
    - 960
    - 1280
    stride_stages:
    - 1
    - 2
    - 2
    - 2
    - 1
    - 2
    act_stages:
    - relu
    - relu
    - relu
    - h_swish
    - h_swish
    - h_swish
    se_stages:
    - false
    - false
    - true
    - false
    - true
    - true
    width_mult: 1.0
    num_classes: 1000
  mutator_cfg:
    _target_: hyperbox.mutator.random_mutator.RandomMutator
  optimizer_cfg:
    _target_: hyperbox.optimizers.lamb.Lamb
    lr: 0.001
    betas:
    - 0.9
    - 0.999
    eps: 1.0e-06
    weight_decay: 0.0005
    adam: false
  metric_cfg:
    _target_: hyperbox.utils.metrics.Accuracy
  loss_cfg:
    _target_: hyperbox.losses.ce_labelsmooth_loss.CrossEntropyLabelSmooth
    label_smoothing: 0.1
  _target_: hyperbox.models.ofa_model.OFAModel
  scheduler_cfg:
    _target_: hyperbox.schedulers.warmup_scheduler.GradualWarmupScheduler
    multiplier: 1
    warmup_epoch: 10
    after_scheduler:
      _target_: torch.optim.lr_scheduler.CosineAnnealingLR
      T_max: 180
      eta_min: 0.0001
  supernet_epoch: 180
  is_warmup_lr: true
  is_sync: false
  is_net_parallel: false
datamodule:
  _target_: hyperbox.datamodules.imagenet_datamodule.ImagenetDataModule
  data_dir: /datasets/imagenet2012/raw
  classes: 1000
  image_size: 224
  batch_size: 64
  shuffle: true
  pin_memory: true
  drop_last: false
  num_workers: 8
callbacks:
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val/acc
    save_top_k: 1
    save_last: true
    mode: max
    verbose: false
    dirpath: checkpoints/
    filename: '{epoch:02d}_{val/acc:.4f}'
  early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: val/acc
    patience: 200
    mode: max
    min_delta: 0
logger:
  wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    project: OFAMBV3_reproduce
    name: horovod_g4_bs64_Supernetonly_v100_lr0.001_lamb
    save_dir: .
    offline: True
    id: null
    log_model: false
    prefix: ''
    job_type: train
    group: ''
    tags: []
seed: 888
work_dir: ${hydra:runtime.cwd}
data_dir: ${work_dir}/data/
debug: false
print_config: true
ignore_warnings: true
